"""add auth_code

Revision ID: 3c29bc20a54b
Revises: 418d3e637b63
Create Date: 2026-08-28 11:08:22.930370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c29bc20a54b'
down_revision: Union[str, Sequence[str], None] = '418d3e637b63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('code_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_code_user_id'), 'auth_code', ['user_id'], unique=False)
    op.create_index('uq_auth_code_live', 'auth_code', ['user_id', 'purpose'], unique=True, postgresql_where=sa.text('consumed_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_auth_code_live', table_name='auth_code', postgresql_where=sa.text('consumed_at IS NULL'))
    op.drop_index(op.f('ix_auth_code_user_id'), table_name='auth_code')
    op.drop_table('auth_code')
    # ### end Alembic commands ###
