"""add watchlist_item

Revision ID: 4f83414b3ba9
Revises: e37ce00b2971
Create Date: 2026-08-25 13:07:03.002904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f83414b3ba9'
down_revision: Union[str, Sequence[str], None] = 'e37ce00b2971'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watchlist_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'asset_id', name='uq_watchlist_item_user_asset')
    )
    op.create_index(op.f('ix_watchlist_item_asset_id'), 'watchlist_item', ['asset_id'], unique=False)
    op.create_index(op.f('ix_watchlist_item_user_id'), 'watchlist_item', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_item_user_id'), table_name='watchlist_item')
    op.drop_index(op.f('ix_watchlist_item_asset_id'), table_name='watchlist_item')
    op.drop_table('watchlist_item')
    # ### end Alembic commands ###
