"""add provider_fetch_log

Revision ID: 626b7647980e
Revises: ae9f6fe6b10d
Create Date: 2026-08-23 14:11:04.661116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '626b7647980e'
down_revision: Union[str, Sequence[str], None] = 'ae9f6fe6b10d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_fetch_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('ttl_seconds', sa.Integer(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_fetch_log_asset_id'), 'provider_fetch_log', ['asset_id'], unique=False)
    op.create_index('ix_provider_fetch_log_provider_fetched_at', 'provider_fetch_log', ['provider', 'fetched_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_provider_fetch_log_provider_fetched_at', table_name='provider_fetch_log')
    op.drop_index(op.f('ix_provider_fetch_log_asset_id'), table_name='provider_fetch_log')
    op.drop_table('provider_fetch_log')
    # ### end Alembic commands ###
