"""add sector_index_pe

Revision ID: 7a341528efea
Revises: a64c37056366
Create Date: 2026-08-25 10:33:45.096264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a341528efea'
down_revision: Union[str, Sequence[str], None] = 'a64c37056366'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sector_index_pe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index_name', sa.String(), nullable=False),
    sa.Column('pe', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pb', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('div_yield', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('index_date', sa.Date(), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('index_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sector_index_pe')
    # ### end Alembic commands ###
