"""initial schema: asset, instrument_map, industry, company, price_ohlcv, corporate_action

Revision ID: ae9f6fe6b10d
Revises: 
Create Date: 2026-08-23 14:05:12.264747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae9f6fe6b10d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('exchange', sa.String(), nullable=False),
    sa.Column('market', sa.String(), nullable=False),
    sa.Column('asset_class', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('isin', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isin'),
    sa.UniqueConstraint('market', 'exchange', 'symbol', name='uq_asset_market_exchange_symbol')
    )
    op.create_index(op.f('ix_asset_symbol'), 'asset', ['symbol'], unique=False)
    op.create_table('industry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('score_profile_key', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('company',
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('industry_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('mgmt_notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['industry_id'], ['industry.id'], ),
    sa.PrimaryKeyConstraint('asset_id')
    )
    op.create_table('corporate_action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('ex_date', sa.Date(), nullable=False),
    sa.Column('ratio', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_corporate_action_asset_ex_date', 'corporate_action', ['asset_id', 'ex_date'], unique=False)
    op.create_table('instrument_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('provider_instrument_key', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_instrument_key', name='uq_instrument_map_key')
    )
    op.create_index(op.f('ix_instrument_map_asset_id'), 'instrument_map', ['asset_id'], unique=False)
    op.create_table('price_ohlcv',
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('high', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('low', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('oi', sa.BigInteger(), nullable=True),
    sa.Column('adj_close', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('delivery_qty', sa.BigInteger(), nullable=True),
    sa.Column('delivery_pct', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('asset_id', 'date')
    )
    op.create_index('ix_price_ohlcv_date', 'price_ohlcv', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_price_ohlcv_date', table_name='price_ohlcv')
    op.drop_table('price_ohlcv')
    op.drop_index(op.f('ix_instrument_map_asset_id'), table_name='instrument_map')
    op.drop_table('instrument_map')
    op.drop_index('ix_corporate_action_asset_ex_date', table_name='corporate_action')
    op.drop_table('corporate_action')
    op.drop_table('company')
    op.drop_table('industry')
    op.drop_index(op.f('ix_asset_symbol'), table_name='asset')
    op.drop_table('asset')
    # ### end Alembic commands ###
