"""add financial_statement and financial_metric

Revision ID: ccd4d9807241
Revises: 626b7647980e
Create Date: 2026-08-23 15:53:49.781102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccd4d9807241'
down_revision: Union[str, Sequence[str], None] = '626b7647980e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_metric',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('metric', sa.String(), nullable=False),
    sa.Column('value', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'metric', name='uq_financial_metric_asset_metric')
    )
    op.create_index(op.f('ix_financial_metric_asset_id'), 'financial_metric', ['asset_id'], unique=False)
    op.create_table('financial_statement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('period_type', sa.String(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('statement_type', sa.String(), nullable=False),
    sa.Column('line_item', sa.String(), nullable=False),
    sa.Column('value', sa.Numeric(precision=24, scale=4), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'period_type', 'period_end', 'statement_type', 'line_item', name='uq_financial_statement_line')
    )
    op.create_index(op.f('ix_financial_statement_asset_id'), 'financial_statement', ['asset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_financial_statement_asset_id'), table_name='financial_statement')
    op.drop_table('financial_statement')
    op.drop_index(op.f('ix_financial_metric_asset_id'), table_name='financial_metric')
    op.drop_table('financial_metric')
    # ### end Alembic commands ###
