"""add alert

Revision ID: e69473ff3e99
Revises: 1c6a84df5044
Create Date: 2026-08-26 02:19:39.877603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e69473ff3e99'
down_revision: Union[str, Sequence[str], None] = '1c6a84df5044'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('dedup_key', sa.String(), nullable=False),
    sa.Column('thesis_event_id', sa.Integer(), nullable=True),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thesis_event_id'], ['thesis_event.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'dedup_key', name='uq_alert_user_dedup_key')
    )
    op.create_index(op.f('ix_alert_asset_id'), 'alert', ['asset_id'], unique=False)
    op.create_index(op.f('ix_alert_user_id'), 'alert', ['user_id'], unique=False)
    op.create_index('ix_alert_user_unread', 'alert', ['user_id'], unique=False, postgresql_where=sa.text('read_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alert_user_unread', table_name='alert', postgresql_where=sa.text('read_at IS NULL'))
    op.drop_index(op.f('ix_alert_user_id'), table_name='alert')
    op.drop_index(op.f('ix_alert_asset_id'), table_name='alert')
    op.drop_table('alert')
    # ### end Alembic commands ###
