"""add thesis tracker tables

Revision ID: f7284cf7be4f
Revises: 4f83414b3ba9
Create Date: 2026-08-25 14:44:49.620513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7284cf7be4f'
down_revision: Union[str, Sequence[str], None] = '4f83414b3ba9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thesis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('stance', sa.String(), nullable=False),
    sa.Column('conviction', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thesis_asset_id'), 'thesis', ['asset_id'], unique=False)
    op.create_index('ix_thesis_status', 'thesis', ['status'], unique=False)
    op.create_index(op.f('ix_thesis_user_id'), 'thesis', ['user_id'], unique=False)
    op.create_table('thesis_trigger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thesis_id', sa.Integer(), nullable=False),
    sa.Column('metric', sa.String(), nullable=False),
    sa.Column('operator', sa.String(), nullable=False),
    sa.Column('threshold', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('currently_breached', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['thesis_id'], ['thesis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thesis_trigger_thesis_id'), 'thesis_trigger', ['thesis_id'], unique=False)
    op.create_table('thesis_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thesis_id', sa.Integer(), nullable=False),
    sa.Column('trigger_id', sa.Integer(), nullable=False),
    sa.Column('fired_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('observed_value', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['thesis_id'], ['thesis.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trigger_id'], ['thesis_trigger.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thesis_event_thesis_id'), 'thesis_event', ['thesis_id'], unique=False)
    op.create_index(op.f('ix_thesis_event_trigger_id'), 'thesis_event', ['trigger_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_thesis_event_trigger_id'), table_name='thesis_event')
    op.drop_index(op.f('ix_thesis_event_thesis_id'), table_name='thesis_event')
    op.drop_table('thesis_event')
    op.drop_index(op.f('ix_thesis_trigger_thesis_id'), table_name='thesis_trigger')
    op.drop_table('thesis_trigger')
    op.drop_index(op.f('ix_thesis_user_id'), table_name='thesis')
    op.drop_index('ix_thesis_status', table_name='thesis')
    op.drop_index(op.f('ix_thesis_asset_id'), table_name='thesis')
    op.drop_table('thesis')
    # ### end Alembic commands ###
