"""add score_profile, score, score_component

Revision ID: fafb43682830
Revises: cc8a14b92a49
Create Date: 2026-08-23 16:38:12.048340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fafb43682830'
down_revision: Union[str, Sequence[str], None] = 'cc8a14b92a49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('score_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('industry_code', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('weights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('industry_code', 'version', name='uq_score_profile_industry_version')
    )
    op.create_table('score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('coverage', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['score_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_score_asset_as_of', 'score', ['asset_id', 'as_of'], unique=False)
    op.create_index(op.f('ix_score_asset_id'), 'score', ['asset_id'], unique=False)
    op.create_table('score_component',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score_id', sa.Integer(), nullable=False),
    sa.Column('component', sa.String(), nullable=False),
    sa.Column('raw_value', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('normalized_value', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('weight', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('contribution', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['score_id'], ['score.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_score_component_score_id'), 'score_component', ['score_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_score_component_score_id'), table_name='score_component')
    op.drop_table('score_component')
    op.drop_index(op.f('ix_score_asset_id'), table_name='score')
    op.drop_index('ix_score_asset_as_of', table_name='score')
    op.drop_table('score')
    op.drop_table('score_profile')
    # ### end Alembic commands ###
